# ── Configuration ──────────────────────────────────────────
QUESTION_COUNT = 5

DIFFICULTY = {
    "Basic":        int(QUESTION_COUNT * 0.6),
    "Intermediate": int(QUESTION_COUNT * 0.3),
    "Hard":         QUESTION_COUNT - int(QUESTION_COUNT * 0.6) - int(QUESTION_COUNT * 0.3),
}

# ── Prompts ────────────────────────────────────────────────

def interview_question_prompt(role: str) -> str:

    difficulty_lines = "\n".join(
        f"- {count} {level} question{'s' if count > 1 else ''}"
        for level, count in DIFFICULTY.items()
        if count > 0
    )

    numbered_format = "\n".join(
        f"Q{i}. <question>" for i in range(1, QUESTION_COUNT + 1)
    )

    return f"""
You are an AI interviewer.

Generate exactly {QUESTION_COUNT} interview questions for the role: {role}.

Difficulty distribution:
{difficulty_lines}

Rules:
- Questions must be commonly asked in real interviews.
- Each question must be under 20 words.
- Focus on practical topics relevant to the role.
- ALL questions must be answerable VERBALLY in a spoken interview.
- Do NOT ask questions that require writing code, designing systems, or drawing diagrams.
- Do NOT ask "implement", "write", "design", "build", "create", or "code" questions.
- Ask concept-based, experience-based, or explanation-based questions only.
- Example GOOD: "What is the difference between list and tuple in Python?"
- Example BAD: "Implement a function to find the maximum value in a nested list."

STRICT OUTPUT RULES:
- Output ONLY the questions — no intro, no explanation, no extra text.

Output format (exactly):
{numbered_format}
"""


def interview_feedback_prompt(role: str, interview_data) -> str:

    return f"""
You are a senior technical interviewer evaluating a spoken mock interview.

Role: {role}
Total Questions: {QUESTION_COUNT}

Candidate Responses:
{interview_data}

SCORING PHILOSOPHY:
This is a SPOKEN interview — not a written exam.
The transcript is generated by speech recognition and may contain minor errors.
Judge the INTENT and MEANING of the answer, not the exact words or spelling.
If the answer clearly conveys the correct concept, give score of 1.
Only score 0 if the candidate clearly has NO understanding of the concept at all.
Be lenient with filler words, grammar, and sentence structure — this is spoken English.

Scoring guide (STRICT — only 0 or 1):
0 → Candidate clearly has NO understanding — completely wrong or no answer provided
1 → Candidate demonstrates correct understanding of the core concept

Empty or very short answers (< 5 characters):
- correctness: "Incorrect"
- score: 0
- feedback: "No answer was provided."

Evaluation Instructions:
1. Evaluate ALL {QUESTION_COUNT} questions in order.
2. Extract the KEY CONCEPT the question is testing.
3. Check if the candidate's answer covers that key concept — regardless of length.
4. Score is ONLY 0 or 1 — no other values allowed.
5. feedback: 1 sentence — what was correct or what key point was missing.
6. better_answer: 1–2 sentences max — the ideal concise spoken answer.

Return ONLY a valid JSON object in this exact shape — no markdown, no code fences, no extra text:

{{
  "overall_score": <sum of all scores, max = {QUESTION_COUNT}>,
  "overall_summary": "<2-3 sentence summary focusing on conceptual understanding>",
  "questions": [
    {{
      "question": "<question text>",
      "candidate_answer": "<candidate answer or empty string>",
      "correctness": "<Correct | Incorrect>",
      "score": <0 or 1 only>,
      "feedback": "<1 sentence>",
      "better_answer": "<1-2 sentence ideal spoken answer>"
    }}
  ]
}}

Rules:
- Output ONLY the JSON. Nothing before or after it.
- Do NOT fabricate or modify candidate answers.
- score per question is ONLY 0 or 1.
- overall_score = sum of all question scores (max = {QUESTION_COUNT}).
- questions array must contain exactly {QUESTION_COUNT} items.
- correctness is ONLY "Correct" or "Incorrect" — no "Partially Correct".
"""